name: Aladdin Scheduled Task

on:
  schedule:
      - cron: "0 */6 * * *" 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 40  # hard limit to prevent exceeding 40 minutes

    env:
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        ASSOCIATED_APP: ${{ secrets.ASSOCIATED_APP }}
        USER_ID: ${{ secrets.USER_ID }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}


    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
    
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: |
          source .venv/bin/activate
          python -m src.main
