name: Aladdin Scheduled Task

on:
  schedule:
    # 6:00 AM IST = 12:30 AM UTC 
    - cron: '30 0 * * *'
    # 10:00 PM IST = 4:30 PM UTC
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    # Run only when on 'feat/supabase' branch
    if: github.ref == 'refs/heads/feat/supabase'

    env:
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        ASSOCIATED_APP: ${{ secrets.ASSOCIATED_APP }}
        USER_ID: ${{ secrets.USER_ID }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}


    steps:
      - name: Checkout feat/supabase branch
        uses: actions/checkout@v4
        with:
          ref: feat/supabase

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
    
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: |
          source .venv/bin/activate
          python -m src.main
